# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlHv2ZYURrWKfeWZ-u8Xom_n8oqyaT6C
"""

print("Ola, Mundo")

num1 = int(input("Digite o 1 numero "))
num2 = int(input("Digite o 2 numero "))
soma = num1 + num2
print("A soma e:",soma)

nota1 = float(input("Digite o 1 numero: "))
nota2 = float(input("Digite o 2 numero: "))
nota3 = float(input("Digite o 1 numero: "))

media = (nota1 + nota2 + nota3) / 3

print("A media é ",media)

if media >= 7:
  print("Aprovado ",media)
elif media >= 5:
  print("Recuperaçao ",media)
else:
  print("Reprovado ",media)

import random
numero_secreto = random.randint(1,100)
palpite = 0

while palpite != numero_secreto:
  palpite = int(input("Adivinhe um numero entre 1 e 10. "))

  if palpite < numero_secreto:
    print("O numero e maior tente novamente")
  elif palpite > numero_secreto:
    print("O numero e menor tente novamente.")
  else:
    print("Parabens, voce e gay!!!")

nota1 = float(input("Digite o 1 numero: "))
nota2 = float(input("Digite o 2 numero: "))
operacao = input("Digite a operacao (+,-,/,*)")

if operacao == "+":
  print("O resultado e ", nota1 + nota2)
elif operacao == "-":
  print("O resultado e ", nota1 - nota2)
elif operacao == "*":
  print("O resultado e ", nota1 * nota2)
elif operacao == "/":
  if nota2 != 0:
    print("O resultado e ", nota1 / nota2)
  else:
    print("Erro: Divisão por zero!")
else:
  print("Operação inválida.")

quadrado = float(input("Digite o valor do lado do quadrado? "))
lado = quadrado * quadrado
print(f"A area do quadrado é: {lado}")
print(f"O dobro da area é: {lado * 2}")
print(f"O triplo da area é: {lado * 3}")

numero = int(input("Digite um numero: "))

if numero % 2 == 0:
  print("O numero e par.")
else:
  print("O numero e impar.")

nota1 = float(input("Digite o 1 numero: "))
nota2 = float(input("Digite o 2 numero: "))
nota3 = float(input("Digite o 1 numero: "))
media = (nota1 + nota2 + nota3) / 3
print("A media e: ",media)

num1 = float(input("Digite o 1 numero: "))
num2 = float(input("Digite o 2 numero: "))
num3 = float(input("Digite o 1 numero: "))

maior = max(num1, num2, num3)
print("A maxima e: ",maior)

nomes = []
nomes.append("Ana")
nomes.append("Carlos")
nomes.append("Maria")
print(f"Lista de nomes: {nomes}")

cores = ["azul", "verde", "vermelho"]
cores.insert(1, "amarelo")
print(f"Lista de cores atualizada: {cores}")

frutas = ["maçã", "banana", "uva", "laranja"]
frutas.remove("banana")
print(f"Frutas após remoção: {frutas}")

numeros = [10, 20, 30, 40, 50]
removido = numeros.pop()
print(f"Número removido: {removido}")
print(f"Lista atual: {numeros}")

cidades = ["Belo Horizonte", "São Paulo", "Rio de Janeiro"]
cidades[1] = "Curitiba"
print(f"Lista atualizada: {cidades}")

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista1.extend(lista2)
print(f"Lista unida: {lista1}")

nomes = ["Ana", "Carlos", "Maria"]
if "Carlos" in nomes:
    print(f"Carlos está na lista")
else:
    print(f"Carlos não está na lista")

numeros = [5, 2, 9, 1, 7]
numeros.sort()
print(f"Lista ordenada: {numeros}")
numeros.reverse()
print(f"Lista invertida: {numeros}")

numeros = [10, 20, 30, 20, 40, 20]
quantidade = numeros.count(20)
posicao = numeros.index(20)
print(f"O número 20 apareceu {quantidade} vezes")
print(f"Primeira posição do 20: {posicao}")

lista = ["a", "b", "c", "d", "e"]
print(f"Tamanho da lista: {len(lista)}")
lista.clear()
print(f"Lista após limpar: {lista}")
print(f"Tamanho após limpar: {len(lista)}")

alunos = ["Ana", "Carlos", "Maria", "João", "Pedro"]
for posicao, nome in enumerate(alunos, start=1):
    print(f"Aluno {posicao}: {nome}")

alunos = ["Fabio", "Eliaz", "Lucas", "Tuzao", "Pietro"]
for posicao, nome in enumerate(alunos, start=1):
    print(f"Aluno{posicao}: {nome}, Acesso liberado.")

alunos = ["Fabio", "Eliaz", "Lucas", "Tuzao", "Pietro"]

print(f"O primeiro aluno é: {alunos[0]}")
print(f"O terceiro aluno é: {alunos[2]}")
print(f"O último aluno é: {alunos[4]}")

alunos = ["Fabio", "Eliaz", "Lucas", "Tuzao", "Pietro"]

alunos[1] = "Mariana"
print(f"Lista atualizada: {alunos}")

alunos = ["Fabio", "Eliaz", "Lucas", "Tuzao", "Pietro"]

alunos[1] = "Mariana"
print(f"Lista atualizada: {alunos}")
alunos.append("Vitor")
print(f"Após adicionar um aluno: {alunos}")
alunos.pop(1)
print(f"Após remover o segundo aluno: {alunos}")

numeros = [42, 7, 19, 3, 25]

numeros.sort()
print(f"Lista ordenada em ordem crescente: {numeros}")

numeros = [42, 7, 19, 3, 25]

numeros.sort(reverse = True)
print(f"Lista ordenada em ordem crescente: {numeros}")